// <auto-generated />
using System;
using Backend.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Srbopoly_backend.Migrations
{
    [DbContext(typeof(SrbopolyContext))]
    partial class SrbopolyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Persistence.Entities.BoardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.CardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameCardID")
                        .HasColumnType("int");

                    b.Property<int?>("GameEntityID")
                        .HasColumnType("int");

                    b.Property<int?>("GameEntityID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameEntityID");

                    b.HasIndex("GameEntityID1");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.FieldEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BoardEntityID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("FieldType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameFieldID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BoardEntityID");

                    b.ToTable("Fields");

                    b.HasDiscriminator().HasValue("FieldEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Persistence.Entities.GameEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BoardID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("int");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BoardID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int?>("GameEntityID")
                        .HasColumnType("int");

                    b.Property<bool>("IsInJail")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameEntityID");

                    b.HasIndex("UserID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PropertyFieldEntity", b =>
                {
                    b.HasBaseType("Backend.Persistence.Entities.FieldEntity");

                    b.Property<int>("Hotels")
                        .HasColumnType("int");

                    b.Property<int>("Houses")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("int");

                    b.HasIndex("OwnerID");

                    b.HasDiscriminator().HasValue("PropertyFieldEntity");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.CardEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.GameEntity", null)
                        .WithMany("RewardCardsDeck")
                        .HasForeignKey("GameEntityID");

                    b.HasOne("Backend.Persistence.Entities.GameEntity", null)
                        .WithMany("SurpriseCardsDeck")
                        .HasForeignKey("GameEntityID1");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.FieldEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.BoardEntity", null)
                        .WithMany("ChangeableFields")
                        .HasForeignKey("BoardEntityID");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.GameEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.BoardEntity", "Board")
                        .WithMany()
                        .HasForeignKey("BoardID");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PlayerEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.GameEntity", null)
                        .WithMany("Players")
                        .HasForeignKey("GameEntityID");

                    b.HasOne("Backend.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PropertyFieldEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.PlayerEntity", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerID");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.BoardEntity", b =>
                {
                    b.Navigation("ChangeableFields");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.GameEntity", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("RewardCardsDeck");

                    b.Navigation("SurpriseCardsDeck");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
