package com.example.srbopoly.enums


enum class FieldType {
    START, JAIL, PARKING, GO_TO_JAIL,
    REWARD, CHANCE, NATIONAL_PARK, TAX,
    ELECTRIC_TAX, WATER_TAX,
    VOJVODINA, ISTOCNA_SRBIJA, JUZNA_SRBIJA, KIM,
    SUMADIJA, ZAPADNA_SRBIJA, PREMIUM1, PREMIUM2
}